name: Build and Deploy to Droplet

on:
  push:
    branches:
      - deploy

env:
  IMAGE_NAME: ghcr.io/jagustinus/face-symmetry-analyzer

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy_to_droplet:
    needs: build_and_push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}

            # Log in to the GitHub Container Registry from the server
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            
            # Pull the latest version of the image from the registry
            docker pull ${{ env.IMAGE_NAME }}:latest
            
            # Restart the service using the new image
            # No --build flag needed!
            docker compose up -d
            
            # Clean up old, unused images
            docker image prune -f
            
            echo "✅ Deployment successful!"